### ISSUE TITLE
Problem connection, no example

### ISSUE THREAD

**Issue by anomal3** [adrenak/univoice-mirror-network#2]
I’m sure that your sdk works, it’s my hands that are crooked) But without an example I can’t make the connection. 
Or am I missing something?

My connection code looks like this
```cs
public class VoiceChat : MonoBehaviour
{
    public ChatroomAgent agent;

    IEnumerator Start()
    {
        InitializeAgent();

        yield return new WaitForSeconds(5);
        if (agent.CurrentMode != ChatroomAgentMode.Host)
        {
            agent.Network.OnJoinedChatroom += Network_OnJoinedChatroom;
            agent.Network.OnChatroomJoinFailed += Network_OnChatroomJoinFailed;
        }
    }

    private void Network_OnChatroomJoinFailed(System.Exception obj)
    {
        Debug.LogWarning("!!!!!!!!!!!" + obj.Message);
    }

    private void Network_OnJoinedChatroom(short obj)
    {
        Debug.Log("Im connect");
    }


    void InitializeAgent()
    {
        agent = new ChatroomAgent(
            new UniVoiceMirrorNetwork(),
            new UniVoiceUniMicInput(0, 8000, 50),
            new UniVoiceAudioSourceOutput.Factory()
        );
    }
    
}
```

I end up getting a cyclic error on the client
![client](https://github.com/adrenak/univoice-mirror-network/assets/12729713/e814cdff-d9bc-48a4-b7e9-11279226f2ed)

And this is the error on the server:
![server](https://github.com/adrenak/univoice-mirror-network/assets/12729713/dfac2e4a-7718-49b6-86c4-0a9f522f809e)

**What did I do wrong?**

**Comment by anomal3** [comment]
I figured it out. I didn't understand the note a bit. But without a living example, understanding comes very difficult. 
```cs
 agent = new ChatroomAgent(
     new UniVoiceMirrorNetwork(),
     new UniVoiceUniMicInput(0, 4000, 20),
     new UniVoiceAudioSourceOutput.Factory()
 );
```

How can I, for example, make sound play from the desired AudioSource?

**Comment by adrenak** [comment]
Hi @anomal3 the issue you faced initially is was that the packet size was too large.

Audio sampled at 8000Hz broken up into 50ms chunks is 8000 * 0.05 = 400 samples being sent every 50ms.

Since each sample is a float, that brings your audio packet size to 1600bytes. 

Depending on the transport you select on Mirror, that will exceed the limit. By reducing it to 20 ms, you have brought it down to 160 samples (640 bytes). 

I'd recommend trying setting it to 40ms and seeing if that crosses the limit. Higher segment duration can help with transmission when latency fluctuates.

Regarding your second comment, you're currently using `UnivoiceAudioSourceOutput.Factory()`, which creates a new audio source for every peer [here](https://github.com/adrenak/univoice-audiosource-output/blob/b57ac8dea3f7e805e07724cf2b3805b24e61fa71/Assets/Adrenak.UniVoice.AudioSourceOutput/Runtime/UniVoiceAudioSourceOutput.cs#L186)

Please note that _each_ peer requires a _different_ audio source. The factory you're currently using already does that.

If you want to use a specific audio source (maybe you have a pool of AudioSource instances?), you can create your own implementation of the `IAudioOutputFactory` interface and use that instead.

**Comment by QoQnous** [comment]
> Hi @anomal3 the issue you faced initially is was that the packet size was too large.
> 
> Audio sampled at 8000Hz broken up into 50ms chunks is 8000 * 0.05 = 400 samples being sent every 50ms.
> 
> Since each sample is a float, that brings your audio packet size to 1600bytes.
> 
> Depending on the transport you select on Mirror, that will exceed the limit. By reducing it to 20 ms, you have brought it down to 160 samples (640 bytes).
> 
> I'd recommend trying setting it to 40ms and seeing if that crosses the limit. Higher segment duration can help with transmission when latency fluctuates.
> 
> Regarding your second comment, you're currently using `UnivoiceAudioSourceOutput.Factory()`, which creates a new audio source for every peer [here](https://github.com/adrenak/univoice-audiosource-output/blob/b57ac8dea3f7e805e07724cf2b3805b24e61fa71/Assets/Adrenak.UniVoice.AudioSourceOutput/Runtime/UniVoiceAudioSourceOutput.cs#L186)
> 
> Please note that _each_ peer requires a _different_ audio source. The factory you're currently using already does that.
> 
> If you want to use a specific audio source (maybe you have a pool of AudioSource instances?), you can create your own implementation of the `IAudioOutputFactory` interface and use that instead.

Hi Adranak, first of all, I would like to thank you for the free tools you provide.  I encountered the same problem during the initial test (large volume of sent packets), then I set the values ​​to 4000 and 25.  Communication was established, but the quality of the sounds was extremely low and weak.  (Of course, this test was done by me on the local network).  What solution do you have to improve the sound quality?

**Comment by QoQnous** [comment]
Hi @adrenak ,
first of all, I would like to thank you for the free tools you provide. ❤️🌱
I encountered the same problem during the initial test (large volume of sent packets), then I set the values to 4000 and 25. Communication was established, but the quality of the sounds was extremely low and weak. (Of course, this test was done by me on the local network). What solution do you have to improve the sound quality?

**Comment by adrenak** [comment]
Hi @QoQnous, always glad to share things with the community :)

4000Hz is super low. 8000Hz should get you decent quality and 16000Hz is ideal for voice (IIRC whatsapp and other calling apps use that)

Using the formula I wrote in the comment above, you'd want the packet size to be reasonable, so you can try these:
* 8000Hz, 40ms. This is 8000 * 0.04 * 4 = 1280bytes
* 16000Hz, 20ms. This is 16000 * 0.02 * 4 = 1280bytes

**Comment by QoQnous** [comment]
Hello again,
I changed the numbers according to your instructions and got good sound quality.  Now the only problem here is that the sound is heard in pieces and does not have good clarity (of course, this does not mean that the sound quality is low and the sound quality is good).
It seems that this problem can be solved, but it requires high expertise in setting it.  It should be noted that I could not set the 8000 rate to 40ms as you said, because the packets were still larger than the receive window size.  Inevitably I set the numbers to 8000 and 25.  Now I think that the number 25 means that 4 packets are received every second, which causes the number of packets and increases the possibility of their loss (of course, my trial and error is still on the local network).
Dear @adrenak , do you have a solution for this problem?

**Comment by anomal3** [comment]
> Привет@anomal3Изначально проблема, с которой вы столкнулись, заключалась в том, что размер пакета был слишком большим.
> 
> Звук, сэмплированный с частотой 8000 Гц, разбитый на фрагменты по 50 мс, составляет 8000 * 0,05 = 400 сэмплов, отправляемых каждые 50 мс.
> 
> Поскольку каждая выборка представляет собой число с плавающей запятой, размер аудиопакета увеличивается до 1600 байт.
> 
> В зависимости от транспорта, который вы выберете в Mirror, он превысит лимит. Уменьшив его до 20 мс, вы сократили его до 160 выборок (640 байт).
> 
> Я бы порекомендовал попробовать установить значение 40 мс и посмотреть, не превысит ли оно предел. Более высокая длительность сегмента может помочь в передаче при колебаниях задержки.
> 
> Что касается вашего второго комментария, вы сейчас используете `UnivoiceAudioSourceOutput.Factory()`, который создает новый источник звука для каждого узла [здесь.](https://github.com/adrenak/univoice-audiosource-output/blob/b57ac8dea3f7e805e07724cf2b3805b24e61fa71/Assets/Adrenak.UniVoice.AudioSourceOutput/Runtime/UniVoiceAudioSourceOutput.cs#L186)
> 
> Обратите внимание, что для _каждого_ узла требуется _отдельный_ источник звука. Фабрика, которую вы сейчас используете, уже делает это.
> 
> Если вы хотите использовать определенный источник звука (возможно, у вас есть пул экземпляров AudioSource?), вы можете создать свою собственную реализацию интерфейса `IAudioOutputFactory`и использовать ее вместо этого.

Thank you very much for the clarification. But still, for the future, a clear example of a project would be super.

Regarding the package, why not apply compression? send compressed packets, and decompress them when received, I used this practice with text in SignalR where the packet size is also limited to 32Kb. Tests?)))))
